### ISSUE TITLE
Can you explain more about your modified code?

### ISSUE THREAD

**Issue by kevin5645218** [DizzyYunxuan/FSSR#1]
It seems to be a great code.
I wonder about your modification. Can you explain more about your idea?
Thank you :)

**Comment by DizzyYunxuan** [comment]
Thanks for your compliment!
This repo just for me to synchronize codes version on different machines conveniently. Our work are still under reviewing, this repo is a part of but not the final official codes.  
Based on original FSSR codes, I merged different network arch, more training options and losses with this version. 
Hope we can get some good comments and then we will release our final codes.

**Comment by kevin5645218** [comment]
Thanks for your response
I hope your work can be accepted! :)
Please released the whole code at the time.
